[package]
name = "brentishere41848/pasusgamblingnew"
version = "0.1.8"
description = "Pasus frontend static site for Wasmer Edge"

[dependencies]
"sharrattj/static-web-server" = "1"

[fs]
public = "dist"
