[general]
root = "/public"
compression = true
compression-static = true
cache-control-headers = true
page404 = "/public/404.html"
page-fallback = "/public/index.html"
health = true
redirect-trailing-slash = true
