[package]
name = "brentishere41848/wasmer-api"
version = "0.1.0"
description = "Description for package wasmer-api"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[dependencies]
"quickjs/quickjs" = "*"

[[module]]
name = "wasmer-api"
source = "wasmer-api.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "wasmer-api"
module = "wasmer-api"
runner = "wasi"
